* Code of Conduct

I deeply respect the constructive environment that has been built around the
Rust language and its developers, as such this project follows the same
guidelines as outlined in the [[https://www.rust-lang.org/policies/code-of-conduct][Rust Code of Conduct]], specifically:

- We are committed to providing a friendly, safe and welcoming environment for
  all, regardless of level of experience, gender identity and expression, sexual
  orientation, disability, personal appearance, body size, race, ethnicity, age,
  religion, nationality, or other similar characteristic.
- Please avoid using overtly sexual aliases or other nicknames that might
  detract from a friendly, safe and welcoming environment for all.
- Please be kind and courteous. There’s no need to be mean or rude.
- Respect that people have differences of opinion and that every design or
  implementation choice carries a trade-off and numerous costs. There is seldom
  a right answer.
- Please keep unstructured critique to a minimum. If you have solid ideas you
  want to experiment with, make a fork and see how it works.
- We will exclude you from interaction if you insult, demean or harass anyone.
  That is not welcome behavior. We interpret the term “harassment” as including
  the definition in the Citizen Code of Conduct; if you have any lack of clarity
  about what might be included in that concept, please read their definition. In
  particular, we don’t tolerate behavior that excludes people in socially
  marginalized groups.
- Private harassment is also unacceptable. No matter who you are, if you feel
  you have been or are being harassed or made uncomfortable by a community
  member, please contact one of the channel ops or any of the Rust moderation
  team immediately. Whether you’re a regular contributor or a newcomer, we care
  about making this community a safe place for you and we’ve got your back.
- Likewise any spamming, trolling, flaming, baiting or other attention-stealing
  behavior is not welcome.

* Working on Emacs Taskrunner

I am happy to consider any pull requests which add additional functionality as
long as it is done in a way that keeps an eye toward long term maintenance.

Fork this repository and create a pull request to start a discussion.
Additionally, if you would like to start a lower effort discussion about
potential improvements, feel free to raise a GitHub issue (with tag
'improvement').
